# Exercise 8

In [3]:
!pip install pyECLAT

Requirement already satisfied: pyECLAT in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.0.2)
Requirement already satisfied: pandas>=0.25.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyECLAT) (2.2.3)
Requirement already satisfied: numpy>=1.17.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyECLAT) (2.2.3)
Requirement already satisfied: tqdm>=4.41.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyECLAT) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/yscalify/Library/Python/3.10/lib/python/site-packages (from pandas>=0.25.3->pyECLAT) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=0.25.3->pyECLAT) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=0.25.3->pyECLAT) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/yscalify/Library/Python/3.10/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.17.0)

In [4]:
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning, module="seaborn")
warnings.filterwarnings("ignore", category=Warning)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

from pyECLAT import ECLAT

In [5]:
url = "/Users/yscalify/Downloads/exercise8/pc_games_market_basket.csv"

df = pd.read_csv(url, header=None)
# df = pd.read_csv(url, header=None)
df.head()

,0,1,2,3,4,5
0,No Man's Sky,Left 4 Dead 2,Elden Ring,GTA V,Monster Hunter: World,NaN
1,Red Dead Redemption 2,Counter-Strike 2,Left 4 Dead 2,NaN,NaN,NaN
2,No Man's Sky,Monster Hunter: World,NaN,NaN,NaN,NaN
3,Elden Ring,Divinity: Original Sin 2,Monster Hunter: World,Factorio,Sekiro: Shadows Die Twice,Wolfenstein II
4,Rainbow Six Siege,Doom Eternal,Dark Souls 3,Cyberpunk 2077,BioShock Infinite,NaN

### 1. Generate transaction lists from the dataset

In [6]:
# put your answer here

txns = df.fillna("").values.tolist()
txns = [[item for item in txn if item != ''] for txn in txns]
txns = [[item.strip() for item in txn] for txn in txns]

ids = [i + 1 for i in range(len(txns))]

data =[]
for i, txn in enumerate(txns):
    data.extend([{'TID': ids[i], 'Item': item} for item in txn])

df_txn = pd.DataFrame(data)
df_txn.head(25)

    TID                       Item
0     1               No Man's Sky
1     1              Left 4 Dead 2
2     1                 Elden Ring
3     1                      GTA V
4     1      Monster Hunter: World
5     2      Red Dead Redemption 2
6     2           Counter-Strike 2
7     2              Left 4 Dead 2
8     3               No Man's Sky
9     3      Monster Hunter: World
10    4                 Elden Ring
11    4   Divinity: Original Sin 2
12    4      Monster Hunter: World
13    4                   Factorio
14    4  Sekiro: Shadows Die Twice
15    4             Wolfenstein II
16    5          Rainbow Six Siege
17    5               Doom Eternal
18    5               Dark Souls 3
19    5             Cyberpunk 2077
20    5          BioShock Infinite
21    6            Baldur's Gate 3
22    6   Divinity: Original Sin 2
23    7              Left 4 Dead 2
24    7            Resident Evil 4

### 2. Find the most frequent items

In [7]:
# put your answer here

top_items = df_txn['Item'].value_counts().reset_index()

df_top_items = pd.DataFrame(top_items)
df_top_items.columns = ['Item', 'Count']

total_transactions = len(df)
df_top_items['% Count'] = (df_top_items['Count']*100 / total_transactions).round(2)

df_top_items.style.background_gradient(cmap='Blues')

3. Generate frequent itemsets using ECLAT

In [8]:
# put your answer here

eclat = ECLAT(data=df, verbose=True)

eclat.df_bin.head()

100%|██████████| 74/74 [00:00<00:00, 749.23it/s]
100%|██████████| 74/74 [00:00<00:00, 14116.45it/s]
100%|██████████| 74/74 [00:00<00:00, 7620.95it/s]

,L.A. Noire,Resident Evil 4,The Witcher 3,Dead Cells,Red Dead Redemption 2,Hades,Call of Duty: Modern Warfare 2,RimWorld,Sekiro: Shadows Die Twice,Monster Hunter: World,Counter-Strike 2,Hades,Call of Duty: Modern Warfare 2,Celeste,Cities: Skylines,Half-Life 2,Stardew Valley,The Forest,Cyberpunk 2077,Fallout 4,Baldur's Gate 3,Divinity: Original Sin 2,BioShock Infinite,Subnautica,Skyrim,The Witcher 3,L.A. Noire,Rainbow Six Siege,Quake Champions,Stardew Valley,Sekiro: Shadows Die Twice,Counter-Strike 2,Terraria,Half-Life 2,Dead Cells,Cyberpunk 2077,Elden Ring,Resident Evil 4,Doom Eternal,No Man's Sky,Portal 2,Quake Champions,Rainbow Six Siege,Slay the Spire,BioShock Infinite,Dark Souls 3,Dark Souls 3,Factorio,RimWorld,Fallout 4,No Man's Sky,Baldur's Gate 3,Skyrim,Celeste,Divinity: Original Sin 2,Elden Ring,Wolfenstein II,Subnautica,Left 4 Dead 2,Hollow Knight,Factorio,GTA V,Monster Hunter: World,Cities: Skylines,Red Dead Redemption 2,Left 4 Dead 2,Slay the Spire,Wolfenstein II,GTA V,Doom Eternal,Portal 2,The Forest,Terraria,Hollow Knight
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [9]:
unique_item_list = eclat.uniq_
print(unique_item_list)

[' L.A. Noire', 'Resident Evil 4', ' The Witcher 3', ' Dead Cells', ' Red Dead Redemption 2', ' Hades', 'Call of Duty: Modern Warfare 2', ' RimWorld', 'Sekiro: Shadows Die Twice', 'Monster Hunter: World', ' Counter-Strike 2', 'Hades', ' Call of Duty: Modern Warfare 2', ' Celeste', 'Cities: Skylines', ' Half-Life 2', 'Stardew Valley', ' The Forest', 'Cyberpunk 2077', 'Fallout 4', " Baldur's Gate 3", ' Divinity: Original Sin 2', ' BioShock Infinite', ' Subnautica', ' Skyrim', 'The Witcher 3', 'L.A. Noire', 'Rainbow Six Siege', 'Quake Champions', ' Stardew Valley', ' Sekiro: Shadows Die Twice', 'Counter-Strike 2', 'Terraria', 'Half-Life 2', 'Dead Cells', ' Cyberpunk 2077', 'Elden Ring', nan, ' Resident Evil 4', ' Doom Eternal', "No Man's Sky", ' Portal 2', ' Quake Champions', ' Rainbow Six Siege', ' Slay the Spire', 'BioShock Infinite', ' Dark Souls 3', 'Dark Souls 3', 'Factorio', 'RimWorld', ' Fallout 4', " No Man's Sky", "Baldur's Gate 3", 'Skyrim', 'Celeste', 'Divinity: Original Sin 2', ' Elden Ring', 'Wolfenstein II', 'Subnautica', ' Left 4 Dead 2', 'Hollow Knight', ' Factorio', ' GTA V', ' Monster Hunter: World', ' Cities: Skylines', 'Red Dead Redemption 2', 'Left 4 Dead 2', 'Slay the Spire', ' Wolfenstein II', 'GTA V', 'Doom Eternal', 'Portal 2', 'The Forest', ' Terraria', ' Hollow Knight']

In [10]:
min_support_threshold = 0.002
min_combination = 2
max_combination = 3

4. Show itemsets and support values

In [11]:
# put your answer here

get_ECLAT_indexes, get_ECLAT_supports = eclat.fit(min_support = min_support_threshold, min_combination = min_combination, max_combination = max_combination, separator=' & ', verbose=True)

result = pd.DataFrame(get_ECLAT_supports.items(),columns=['Item', 'Support'])
result = result.sort_values(by=['Support'], ascending=False).reset_index(drop=True)
result

Combination 2 by 2

2701it [00:18, 145.52it/s]

Combination 3 by 3

64824it [04:43, 228.84it/s]

                                                            Item  Support
0                                            Hades &  The Forest   0.0104
1                        The Forest &  Sekiro: Shadows Die Twice   0.0100
2                                               Hades &  Celeste   0.0090
3                 BioShock Infinite &  Sekiro: Shadows Die Twice   0.0088
4                                         Elden Ring &  Terraria   0.0088
...                                                          ...      ...
1561               Call of Duty: Modern Warfare 2 & Doom Eternal   0.0020
1562                              Stardew Valley & Hollow Knight   0.0020
1563                 Call of Duty: Modern Warfare 2 & Subnautica   0.0020
1564   Call of Duty: Modern Warfare 2 & Divinity: Original Sin 2   0.0020
1565                  Elden Ring &  Cities: Skylines &  Terraria   0.0020

[1566 rows x 2 columns]